apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
    - name: gts-matchfrontend
      image: 408181147136.dkr.ecr.ap-northeast-2.amazonaws.com/sandyfloor/gts/matchfrontend:latest
      command: ["printenv"]
      args: ["HOSTNAME", "KUBERNETES_PORT"]
      
    - name: gts-matchfunction
      image: 408181147136.dkr.ecr.ap-northeast-2.amazonaws.com/sandyfloor/gts/matchfunction:latest
      command: [ "printenv" ]
      args: ["HOSTNAME", "KUBERNETES_PORT"]
      
    - name: gts-matchdirector
      image: 408181147136.dkr.ecr.ap-northeast-2.amazonaws.com/sandyfloor/gts/matchdirector:latest
      command: [ "printenv" ]
      args: [ "HOSTNAME", "KUBERNETES_PORT" ]
  restartPolicy: OnFailure