apiVersion: v1
kind: Pod
metadata:
  name: gts-match-cores
  namespace: open-match
  labels:
    purpose: open-match
spec:
  imagePullSecrets:
    - name: regcred
      
  containers:
    - name: gts-matchfrontend
      image: 408181147136.dkr.ecr.ap-northeast-2.amazonaws.com/sandyfloor/gts/matchfrontend:latest
      command: ["printenv\n./front-end"]
      args: ["HOSTNAME", "KUBERNETES_PORT"]
      
    - name: gts-matchfunction
      image: 408181147136.dkr.ecr.ap-northeast-2.amazonaws.com/sandyfloor/gts/matchfunction:latest
      command: [ "printenv\n./match-function" ]
      args: ["HOSTNAME", "KUBERNETES_PORT"]
      
    - name: gts-matchdirector
      image: 408181147136.dkr.ecr.ap-northeast-2.amazonaws.com/sandyfloor/gts/matchdirector:latest
      command: [ "printenv\n./Director" ]
      args: [ "HOSTNAME", "KUBERNETES_PORT" ]
  restartPolicy: OnFailure

---

apiVersion: v1
kind: Service
metadata:
  name: gts-matchfrontend-service
spec:
  type: NodePort
  selector:
    app: gts-matchfrontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8100
      
---

apiVersion: v1
kind: Service
metadata:
  name: gts-matchfunction-service
spec:
  type: NodePort
  selector:
    app: gts-matchfunction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8101
      
---

apiVersion: v1
kind: Service
metadata:
  name: gts-matchdirector-service
spec:
  type: NodePort
  selector:
    app: gts-matchdirector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8102