apiVersion: v1
kind: Pod
metadata:
  name: gts-matchfrontend-cores
  namespace: open-match
  labels:
    purpose: open-match
    app: gts-matchfrontend
spec:
  imagePullSecrets:
    - name: regcred
      
  containers:
    - name: gts-matchfrontend
      image: 408181147136.dkr.ecr.ap-northeast-2.amazonaws.com/sandyfloor/gts/matchfrontend:latest
      command: ["./front-end"]
  restartPolicy: OnFailure
  
---

apiVersion: v1
kind: Pod
metadata:
  name: gts-matchfunction-cores
  namespace: open-match
  labels:
    purpose: open-match
    app: gts-matchfunction
spec:
  imagePullSecrets:
    - name: regcred
  
  containers:
    - name: gts-matchfunction
      image: 408181147136.dkr.ecr.ap-northeast-2.amazonaws.com/sandyfloor/gts/matchfunction:latest
      command: [ "./match-function" ]
  restartPolicy: OnFailure

---

apiVersion: v1
kind: Pod
metadata:
  name: gts-matchdirector-cores
  namespace: open-match
  labels:
    purpose: open-match
    app: gts-matchdirector
spec:
  imagePullSecrets:
    - name: regcred
  
  containers:
    - name: gts-matchdirector
      image: 408181147136.dkr.ecr.ap-northeast-2.amazonaws.com/sandyfloor/gts/matchdirector:latest
      command: [ "./Director" ]
  restartPolicy: OnFailure

---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: gts-matchfrontend-service
#spec:
#  type: NodePort
#  selector:
#    app: gts-matchfrontend
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8100
#      
#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: gts-matchfunction-service
#spec:
#  type: NodePort
#  selector:
#    app: gts-matchfunction
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8101
#      
#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: gts-matchdirector-service
#spec:
#  type: NodePort
#  selector:
#    app: gts-matchdirector
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8102