# restful-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gts-restful
  namespace: gts-lobby-server
  labels:
    app: gts-restful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gts-restful
  template:
    metadata:
      labels:
        app: gts-restful
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: gts-restful
          image: 408181147136.dkr.ecr.ap-northeast-2.amazonaws.com/sandyfloor/gts/restful:test_0.12.1
          env:
            - name: NODE_ENV
              value: production
---
# restful-service
apiVersion: v1
kind: Service
metadata:
  name: my-restful-service
  namespace: gts-lobby-server
spec:
  selector:
    app: gts-restful
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
# socket-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gts-socket
  namespace: gts-lobby-server
  labels:
    app: gts-socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gts-director
  template:
    metadata:
      labels:
        app: gts-director
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: gts-director
          image: 408181147136.dkr.ecr.ap-northeast-2.amazonaws.com/sandyfloor/gts/socket:test_0.12.1
          env:
            - name: NODE_ENV
              value: production