kind: Service
apiVersion: v1
metadata:
  name: gts-front-end
  namespace: open-match
spec:
  type: LoadBalancer
  selector:
    app: gts-front-end
    component: frontend
  ports:
    - port: 51504
      targetPort: 51504
---
kind: Service
apiVersion: v1
metadata:
  name: gts-match-function
  namespace: open-match
  labels:
    app: gts-match-function
    component: matchfunction
spec:
  selector:
    app: gts-match-function
    component: matchfunction
  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: 50502
      targetPort: 50502
    - name: http
      protocol: TCP
      port: 51502
      targetPort: 51502